version: '{build}'

image:
  - Visual Studio 2017
  - Ubuntu

platform:
- x64

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - master

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: false #true
  
build_script:
- ps: .\Build.ps1

artifacts:
  - path: ./phonology_engine/*/*PhonologyEngine.*
  name: phonology-engine-artifacts

deploy:
- provider: GitHub
  tag: phonology-engine-v$(appveyor_build_version)
  release: phonology-engine-v$(appveyor_build_version)
  artifact: phonology-engine-artifacts
  draft: false
  prerelease: false
  auth_token:
    secure: t46UA2N2hilxV8hM/cwfL/WSingfgu3CWV80YHzyKbWdaMTBZmW6hq34+7P6h+XU

skip_tags: true
test: off