version: '{build}'  
image: 
  - Visual Studio 2017
  - Ubuntu
platform:
- x64
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master

environment:  
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:  
- ps: .\Build.ps1
- sh: ./build.sh

test: off  
artifacts:  
- path: .\phonology_engine\Win*_x*\PhonologyEngine.dll
- path: .\phonology_engine\Linux_x*\libPhonologyEngine.so
